"""add sticker tables

Revision ID: 34ac9bf1c5f8
Revises: 474298be8931
Create Date: 2026-03-22 13:51:05.660697
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '34ac9bf1c5f8'
down_revision: Union[str, None] = '474298be8931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
