"""initial schema

Revision ID: 474298be8931
Revises: 
Create Date: 2026-03-22 13:33:52.887595
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '474298be8931'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
