"""add postgis geo columns and course features

Revision ID: bb0a57fd0a1a
Revises: 34ac9bf1c5f8
Create Date: 2026-03-22 14:00:14.417393
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'bb0a57fd0a1a'
down_revision: Union[str, None] = '34ac9bf1c5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Do NOT drop spatial_ref_sys — it's a PostGIS system table
    op.add_column('courses', sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_courses_boundary', 'courses', ['boundary'], unique=False, postgresql_using='gist')
    op.add_column('holes', sa.Column('tee_position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('holes', sa.Column('basket_position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('holes', sa.Column('fairway_line', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('holes', sa.Column('tee_elevation_ft', sa.Float(), nullable=True))
    op.add_column('holes', sa.Column('basket_elevation_ft', sa.Float(), nullable=True))
    op.add_column('holes', sa.Column('elevation_change_ft', sa.Float(), nullable=True))
    op.add_column('holes', sa.Column('elevation_profile', sa.Text(), nullable=True))
    op.create_index('idx_holes_basket_position', 'holes', ['basket_position'], unique=False, postgresql_using='gist')
    op.create_index('idx_holes_fairway_line', 'holes', ['fairway_line'], unique=False, postgresql_using='gist')
    op.create_index('idx_holes_tee_position', 'holes', ['tee_position'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_holes_tee_position', table_name='holes', postgresql_using='gist')
    op.drop_index('idx_holes_fairway_line', table_name='holes', postgresql_using='gist')
    op.drop_index('idx_holes_basket_position', table_name='holes', postgresql_using='gist')
    op.drop_column('holes', 'elevation_profile')
    op.drop_column('holes', 'elevation_change_ft')
    op.drop_column('holes', 'basket_elevation_ft')
    op.drop_column('holes', 'tee_elevation_ft')
    op.drop_column('holes', 'fairway_line')
    op.drop_column('holes', 'basket_position')
    op.drop_column('holes', 'tee_position')
    op.drop_index('idx_courses_boundary', table_name='courses', postgresql_using='gist')
    op.drop_column('courses', 'boundary')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
