#!/usr/bin/env bash
# teammap.sh — Auto-generate real-time Mermaid team map from live state
# Run: ./scripts/teammap.sh
# Output: .claude/coordination/teammap.md
#
# Every Claude Code session should run this:
#   - On session start (after check-in)
#   - After completing a major task
#   - Before picking up new work

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

OUTFILE=".claude/coordination/teammap.md"
NOW=$(date "+%Y-%m-%d %H:%M:%S %Z")

# ── Gather live state ──

CLAUDE_COUNT=$(ps aux | grep -c "[c]laude" 2>/dev/null || echo 0)
PYTEST_PIDS=$(ps aux | grep "[p]ytest" | awk '{print $2}' | tr '\n' ' ' || true)
UVICORN_PID=$(lsof -i :8001 2>/dev/null | grep LISTEN | awk '{print $2}' | head -1 || true)
DB_STATUS=$(docker compose ps --format '{{.Name}} {{.Status}}' 2>/dev/null | grep db | head -1 || echo "unknown")
REDIS_STATUS=$(docker compose ps --format '{{.Name}} {{.Status}}' 2>/dev/null | grep redis | head -1 || echo "unknown")

BRANCH=$(git branch --show-current)
LAST_COMMIT=$(git log --oneline -1)
DIRTY_FILES=$(git diff --name-only HEAD 2>/dev/null | wc -l | tr -d ' ')

# ── Build session table + mermaid nodes ──

TABLE=""
NODES=""
STYLES=""
N=0

for f in .claude/coordination/sessions/*.md; do
    [ -f "$f" ] || continue
    N=$((N + 1))

    NAME=$(grep "^name:" "$f" 2>/dev/null | head -1 | sed 's/name: *//' || echo "unknown")
    ROLE=$(grep "^role:" "$f" 2>/dev/null | head -1 | sed 's/role: *//' | cut -c1-40 || echo "")
    TASK=$(grep "^Currently working on:" "$f" 2>/dev/null | head -1 | sed 's/Currently working on: *//' | cut -c1-50 || echo "idle")
    BLOCKED=$(grep "^Blocked by:" "$f" 2>/dev/null | head -1 | sed 's/Blocked by: *//' || echo "nothing")

    FILE_AGE=$(( $(date +%s) - $(stat -f %m "$f") ))
    if [ "$FILE_AGE" -gt 1800 ]; then
        STATUS="Stale"; COLOR="#9E9E9E"; ICON="gray"
    elif [ "$BLOCKED" != "nothing" ] && [ "$BLOCKED" != "none" ] && [ -n "$BLOCKED" ]; then
        STATUS="Blocked"; COLOR="#FF9800"; ICON="orange"
    else
        STATUS="Active"; COLOR="#4CAF50"; ICON="green"
    fi

    TABLE="${TABLE}| ${NAME} | ${STATUS} | ${TASK} | ${BLOCKED} |
"
    NODES="${NODES}        S${N}[\"${NAME}<br/>${TASK}\"]
"
    STYLES="${STYLES}    style S${N} fill:${COLOR},color:#fff
"
done

# ── Write output ──

cat > "$OUTFILE" << EOF
# Team Map — ${NOW}

> Auto-generated by scripts/teammap.sh. Run \`./scripts/teammap.sh\` to refresh.

## Processes

| Resource | Status |
|----------|--------|
| Claude sessions | ${CLAUDE_COUNT} total |
| Backend API :8001 | PID ${UVICORN_PID:-not running} |
| PostgreSQL | ${DB_STATUS} |
| Redis | ${REDIS_STATUS} |
| pytest running | ${PYTEST_PIDS:-none} |
| Git branch | ${BRANCH} @ ${LAST_COMMIT} |
| Uncommitted files | ${DIRTY_FILES} |

## Sessions

| Name | Status | Current Task | Blocked By |
|------|--------|-------------|------------|
${TABLE}

## Flowchart

\`\`\`mermaid
graph TB
    subgraph Resources
        DB[(PostgreSQL :5433)]
        REDIS[(Redis :6381)]
        API[Backend :8001]
    end

    subgraph Sessions
${NODES}    end

${STYLES}
    style DB fill:#1B5E20,color:#fff
    style REDIS fill:#1B5E20,color:#fff
    style API fill:#1B5E20,color:#fff
\`\`\`
EOF

echo "Teammap updated: ${OUTFILE} (${NOW})"
